Description of Backward
Home > K25104 > LinearSystems > Backward.m
Backward
PURPOSE
Solves the upper triangular system of equations Ax = b
SYNOPSIS
function [x]=Backward(A,b)
DESCRIPTION
 Solves the upper triangular system of equations Ax = b
 Input arguments:
   A, square upper triangular matrix
   b, Ax = b
 Output arguments:
   x solution
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Backward_script Usage example for Backward
Forward_script Usage example for Forward
Gaussian_elementary_script Usage example for Gaussian_elementary
Gaussian_partial_script Usage example for Gaussian_partial
Gaussian_scaledpartial_script Usage example for Gaussian_scaledpartial
Gaussian_total_script Usage example for Gaussian_total
inverse_iteration Implements inverse iteration to find an eigenvalue of A
LU_pivot_script Usage example for LU_pivot
LU_script Usage example for LU
hockney HOCKNEY implements the hockney algorithm without FFT to solve the block
hockney_FFT Implements the Hockney algorithm with FFT to solve the block
SOURCE CODE
function [x]=Backward(A,b)
% Solves the upper triangular system of equations Ax = b
% Input arguments:
%   A, square upper triangular matrix
%   b, Ax = b
% Output arguments:
%   x solution
[n,m]=size(A); % finding the size of A
if n~= m
    error('input is not a square matrix');
end
if size(b,1) ~= n
    error('input dimensions do not match');
end
if ~istriu(A)
    error('matrix is not upper triangular')
end
x = zeros(n,1); % initialize x to the same dimension
if abs(A(n,n)) > 1e-12 % not comparing to zero because of possible
                       % rounding errors
    x(n) = b(n)/A(n,n); % solve for the last element of x
else
    error('input singular'); % A is singular if any of the diagonal
                            % elements are zero
end
for k=n:-1:1 % the loop considers one row after the other backwards
    if abs(A(k,k))>1e-12 % not comparing to zero because of possible
                         % rounding errors
        temp = 0;
        for j=n:-1:k+1
            temp = temp + A(k,j) * x(j); % Multiply the elements of
                                     % the k-th row of A after the
                                     % diagonal by the elements of x
                                     % already calculated
        end
        x(k) = (b(k)-temp)/A(k,k); % solve for the k-th element of x
    else
        error('input singular'); % A is singular if any of the diagonal
                                % elements are zero
    end
end