Description of LU_pivot_script
Home > K25104 > LinearSystems > LU_pivot_script.m
LU_pivot_script
PURPOSE
Usage example for LU_pivot
SYNOPSIS
This is a script file.
DESCRIPTION
 Usage example for LU_pivot
 related to Exercise 2.2
CROSS-REFERENCE INFORMATION
This function calls:
Backward Solves the upper triangular system of equations Ax = b
Forward Solves the lower triangular system of equations Ax = b
LU_pivot Computes the LU factorization with partial pivoting
This function is called by:
SOURCE CODE
% Usage example for LU_pivot
% related to Exercise 2.2
A = [8 6 -2 1;
    8 8 -3 0;
    -2 2 -2 1;
    4 3 -2 5];
b = [-2;
    0;
    2;
    -1];
[L,U,P]=LU_pivot(A);
y = Forward(L,P*b);
x = Backward(U,y)