Description of QRalg_Givens
Home > K25104 > LinearSystems > QRalg_Givens.m
QRalg_Givens
PURPOSE
Performs QR algorithm to deflate matrix A,
SYNOPSIS
function [ D,k ] = QRalg_Givens(A,tol)
DESCRIPTION
 Performs QR algorithm to deflate matrix A,
   QR factorization is performed with Givens Rotations
 Input arguments:
   A, square matrix
   tol, tolerance
 Output arguments:
   D, deflated matrix
   k, number of iterations
CROSS-REFERENCE INFORMATION
This function calls:
QR_Givens Computes the QR factorization of A via Givens rotations
This function is called by:
QRalg_Givens_script_1 Usage example for QRalg_Givens
QRalg_Givens_script_2 Usage example for QRalg_Givens
SOURCE CODE
function [ D,k ] = QRalg_Givens(A,tol)
% Performs QR algorithm to deflate matrix A,
%   QR factorization is performed with Givens Rotations
% Input arguments:
%   A, square matrix
%   tol, tolerance
% Output arguments:
%   D, deflated matrix
%   k, number of iterations
[n,m]=size(A);  % finding the size of A
if n~= m;
    error('input is not a square matrix');
end
U=A; % initialize U to be A
[Q,R]=QR_Givens(U); % this function computes the QR factorization
                    % of U using Givens rotations
U=R*Q; % compute R*Q
% check whether an entry on the first subdiagonal is close to zero
[m,i] = min(abs(diag(U,-1)));
if m<tol    % check whether the (n-i)x(i) bottom left block is
            % close to zero
    m = min(U(i+1:n,1:i));
end
k=1; % initialize counter
while m>tol;
    [Q,R]=QR_Givens(U); % this function computes the QR factorization
                        % of A using Givens rotations
    U=R*Q; % compute RQ
    % check whether an entry on the first subdiagonal is close to zero
    [m,i] = min(abs(diag(U,-1)));
    if m<tol    % check whether the (n-i)x(i) bottom left block is
                % close to zero
        m = min(U(i+1:n,1:i));
    end
k=k+1; % increment counter
end
D=U; % output deflated matrix
end